services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://bankt-1.onrender.com
      - key: L5_SWAGGER_CONST_HOST
        value: https://bankt-1.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: laravel-db
          property: connectionString
      - key: DATABASE_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DATABASE_NAME
        fromDatabase:
          name: laravel-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: laravel-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password

  - type: pserv
    name: laravel-db
    runtime: postgres
    plan: starter
    envVars:
      - key: POSTGRES_DB
        value: laravel
      - key: POSTGRES_USER
        value: laravel
      - key: POSTGRES_PASSWORD
        generateValue: true