services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://bankt-1.onrender.com
      - key: L5_SWAGGER_CONST_HOST
        value: https://bankt-1.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d41b6smr433s73dr9ps0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: banktest_db
      - key: DB_USERNAME
        value: banktest_db_user
      - key: DB_PASSWORD
        value: QplUV4WFifswwOZunv3RRymkVLUlhmoh